version: "2"
run:
  concurrency: 4
  tests: true
linters:
  enable:
    - dupl
    - goconst
    - gocritic
    - gocyclo
    - lll
    - misspell
    - nakedret
    - prealloc
    - revive
    - unparam
  disable:
    - staticcheck
    - unused
    - errcheck
  settings:
    gocritic:
      disabled-checks:
        - ifElseChain
    dupl:
      threshold: 100
    goconst:
      min-len: 3
      min-occurrences: 3
    gocyclo:
      min-complexity: 15
    lll:
      line-length: 200
      tab-width: 1
    revive:
      severity: warning
  exclusions:
    generated: lax
    rules:
      - path: (.+)\.go$
        text: should have comment or be unexported
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
