name: Test and Build
on:
  - push
  - pull_request

jobs:
  default:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.24.0'
      - name: Tests
        run: |
          make fmt
          make vet
          make test
          make build
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.1
      - name: Build release type artifacts
        run: make release
